import { ArrowDownToLine, ArrowUpRight, BookOpen } from "lucide-react";
import Link from "next/link";
import { Reveal } from "./reveal";
import { SectionHeading } from "./section-heading";
import { libraryBooks } from "@/lib/site-data";

export function LibraryPreview() {
  return (
    <section id="biblioteca" className="bg-paper py-24 sm:py-32"><div className="section-shell"><Reveal><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><SectionHeading eyebrow="Recursos libres" title={<>Biblioteca para <span className="text-primary">hacer.</span></>} description="Publicaciones, juegos y herramientas para descargar, adaptar y compartir sin pedir permiso." /><Link href="/biblioteca" className="focus-ring inline-flex shrink-0 items-center gap-2 text-sm font-extrabold text-secondary transition-colors hover:text-primary">Ver biblioteca completa <ArrowUpRight size={16} /></Link></div></Reveal><div className="mt-14 grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3">{libraryBooks.map((book, index) => <Reveal key={book.title} delay={index * 0.05} className={`group relative min-h-[290px] overflow-hidden rounded-[1.6rem] ${book.color} ${book.text} p-5 transition-transform hover:-translate-y-1 sm:min-h-[350px] sm:p-7`}><div className="flex items-start justify-between"><span className="text-3xl font-black opacity-20">{book.number}</span><BookOpen size={21} strokeWidth={1.6} /></div><div className="absolute -right-6 top-16 h-28 w-28 rounded-full border-[18px] border-current opacity-10" /><div className="absolute bottom-5 left-5 right-5 sm:bottom-7 sm:left-7 sm:right-7"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] opacity-60">{book.author}</p><h3 className="display-title mt-3 text-2xl leading-[0.95] sm:text-3xl">{book.title}</h3><div className="mt-6 flex flex-wrap gap-2"><Link href="/biblioteca#recursos" className="focus-ring inline-flex items-center gap-1 rounded-full bg-paper/20 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[0.1em] transition-colors hover:bg-paper/35">Leer <ArrowUpRight size={13} /></Link><Link href="/biblioteca#recursos" className="focus-ring inline-flex items-center gap-1 rounded-full border border-current/25 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[0.1em] transition-colors hover:bg-paper/20"><ArrowDownToLine size={13} /> Descargar</Link></div></div></Reveal>)}</div></div></section>
  );
}
