import { ArrowUpRight, Globe2, UsersRound } from "lucide-react";
import { Reveal } from "./reveal";
import { SectionHeading } from "./section-heading";

export function Partners() {
  return (
    <section className="bg-mist py-24 sm:py-32"><div className="section-shell grid items-center gap-12 lg:grid-cols-[.72fr_1.28fr] lg:gap-24"><Reveal><SectionHeading eyebrow="Más allá de la frontera" title={<>Vínculos <span className="text-secondary">Internacionales</span></>} description="La educación popular también se fortalece cuando cruza idiomas, territorios y maneras de estar en comunidad." /></Reveal><Reveal delay={0.12}><div className="rounded-[2.2rem] bg-paper p-7 shadow-card sm:p-10"><div className="flex flex-col gap-8 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-4"><div className="grid h-20 w-20 place-items-center rounded-2xl bg-primary text-center text-sm font-black leading-none text-white">FPG<br /><span className="text-[8px] font-bold tracking-[0.12em] text-accent">LOGO</span></div><div><h3 className="text-2xl font-extrabold leading-tight">Freier Pfadfinderbund<br />St. Georg</h3><p className="mt-1 text-xs font-bold uppercase tracking-[0.13em] text-ink/45">Organización hermana</p></div></div><ArrowUpRight className="text-primary" size={22} /></div><p className="mt-8 max-w-2xl text-base leading-7 text-ink/65">El FPG comparte con nuestro proyecto la confianza en el escultismo como herramienta de autonomía, responsabilidad y participación. Este vínculo abre conversaciones y aprendizajes entre experiencias educativas distintas.</p><div className="mt-8 grid gap-4 border-t border-ink/10 pt-6 sm:grid-cols-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent"><Globe2 size={19} /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-ink/45">Presencia</p><p className="mt-1 font-bold">Alemania · España</p></div></div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-white"><UsersRound size={19} /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-ink/45">Relación</p><p className="mt-1 font-bold">Aprendizaje compartido</p></div></div></div></div></Reveal></div></section>
  );
}
