import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, UsersRound } from "lucide-react";
import type { CDECommunity } from "@/content/cdes/types";

export function CommunityCard({ cdeSlug, community }: { cdeSlug: string; community: CDECommunity }) {
  const imageClass = "object-cover";

  return <Link href={`/cde/${cdeSlug}/comunidades/${community.id}`} aria-label={`Ver la comunidad ${community.name} del ${cdeSlug}`} className="group block min-w-0"><article className="overflow-hidden rounded-[1.7rem] border border-ink/10 bg-paper shadow-card transition-transform group-hover:-translate-y-1"><div className="relative flex aspect-[4/5] items-center justify-center overflow-hidden bg-white">{community.image ? <Image src={community.image} alt={community.name} fill className={imageClass} sizes="(max-width: 768px) 90vw, 30vw" /> : <div className="flex h-full w-full items-center justify-center bg-ink"><UsersRound className="text-accent" size={48} strokeWidth={1.5} aria-hidden="true" /></div>}</div><div className="border-t border-ink/10 bg-mist/60 px-6 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.15em] text-secondary">Comunidad</p><h3 className="mt-1 break-words text-2xl font-extrabold text-ink">{community.name}</h3></div><span className="rounded-full bg-paper px-3 py-1 text-[10px] font-extrabold uppercase tracking-[0.1em] text-secondary">{community.ageRange}</span></div></div><div className="p-6"><p className="text-sm leading-7 text-ink/60">{community.description}</p>{community.structure ? <p className="mt-4 border-t border-ink/10 pt-4 text-xs leading-6 text-ink/55"><span className="font-extrabold uppercase tracking-[0.12em] text-secondary">Organización · </span>{community.structure}</p> : null}<span className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-secondary transition-colors group-hover:text-primary">Ver comunidad <ArrowUpRight size={16} aria-hidden="true" /></span></div></article></Link>;
}
