import { Eye, Flag, HeartHandshake, Target } from "lucide-react";
import { Reveal } from "@/components/reveal";
import { SectionTitle } from "./section-title";
import { Timeline } from "./timeline";
import type { CDEData } from "@/content/cdes/types";

export function CommunitySection({ cde }: { cde: CDEData }) {
  return <section id="comunidad" className="scroll-mt-36 bg-paper py-20 sm:py-28"><div className="section-shell"><Reveal><SectionTitle eyebrow="01 · Comunidad" title={<>Un lugar para <span className="text-primary">hacer comunidad.</span></>} description={cde.welcome} /></Reveal><div className="mt-14 grid gap-5 lg:grid-cols-[1.08fr_.92fr]"><Reveal delay={0.08} className="rounded-[2rem] bg-mist p-7 sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-secondary">Nuestra historia</p><div className="mt-6 space-y-5 text-base leading-8 text-ink/70">{cde.history.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="mt-8 border-t border-ink/10 pt-7"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-secondary">Filosofía educativa</p><p className="mt-4 text-xl leading-8 text-ink/80">{cde.philosophy}</p></div></Reveal><Reveal delay={0.14} className="rounded-[2rem] bg-secondary p-7 text-white sm:p-10"><div className="flex items-center gap-3"><HeartHandshake className="text-accent" size={24} /><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-accent">Nuestro horizonte</p></div><div className="mt-9 space-y-8"><div><div className="flex items-center gap-2"><Target size={18} className="text-accent" /><h3 className="font-extrabold">Misión</h3></div><p className="mt-3 text-sm leading-7 text-white/70">{cde.mission}</p></div><div className="border-t border-white/15 pt-7"><div className="flex items-center gap-2"><Eye size={18} className="text-accent" /><h3 className="font-extrabold">Visión</h3></div><p className="mt-3 text-sm leading-7 text-white/70">{cde.vision}</p></div></div></Reveal></div><div className="mt-5 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><Reveal className="rounded-[2rem] bg-accent p-7 sm:p-9"><div className="flex items-center gap-3"><Flag size={21} /><p className="text-xs font-extrabold uppercase tracking-[0.16em]">Valores que practicamos</p></div><div className="mt-8 space-y-5">{cde.values.map((value) => <div key={value.label}><h3 className="text-lg font-extrabold">{value.label}</h3><p className="mt-1 text-sm leading-6 text-ink/65">{value.text}</p></div>)}</div></Reveal><Reveal delay={0.08} className="rounded-[2rem] border border-ink/10 bg-paper p-7 shadow-card sm:p-9"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-primary">Línea del tiempo</p><h3 className="display-title mt-4 text-3xl leading-tight">Una historia que sigue<br /><span className="text-secondary">en movimiento.</span></h3><div className="mt-8"><Timeline items={cde.timeline} /></div></Reveal></div></div></section>;
}
